# This file configures the analyzer to use the lint rule set from `package:flutter_lints`

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    - camel_case_types
    - library_names
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - no_duplicate_case_values
    - prefer_void_to_null
    - throw_in_finally
    - valid_regexps

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options